f = open('/app/components/raw_input_form.py')
c = f.read()
f.close()
c = c.replace('    with st.expander("Lag Features", expanded=False):', '    st.markdown("##### Lag Features")\n    if True:')
c = c.replace('    with st.expander("Rolling Average Features", expanded=False):', '    st.markdown("##### Rolling Average Features")\n    if True:')
f = open('/app/components/raw_input_form.py', 'w')
f.write(c)
f.close()
print('DONE')
